### ISSUE TITLE
Building index on larger collection

### ISSUE THREAD

**Issue by donl** [appy-one/acebase#114]
I'm having issues building indexes with larger collections (10k items) with a single Date field.

Error building index /item/*/at: Maximum call stack size exceeded
[idx-test] Index build on "/item/*/at" failed: Maximum call stack size exceeded (code: undefined)
/ace-server-test/node_modules/acebase/src/data-index.js:3801
  const recursiveSort = (start, end) => {
                        ^

RangeError: Maximum call stack size exceeded
    at recursiveSort (/ace-server-test/node_modules/acebase/src/data-index.js:3801:25)

**Comment by appy-one** [comment]
I managed to reproduce this and am on it. Thanks for reporting!

**Comment by appy-one** [comment]
I fixed this by replacing the used quicksort algorithm with a faster variant that uses stacks instead of recursion (which was causing the stack overflow). I've published the changes in v1.21.2. Thanks again for reporting this, let me know if it works! 

Also, **many many** thanks for sponsoring! You rock!!
