### ISSUE TITLE
Migrating from Firebase (cloud functions) to AceBase

### ISSUE THREAD

**Issue by amitnil-developer** [appy-one/acebase#136]
### Discussed in https://github.com/appy-one/acebase/discussions/125

<div type='discussions-op-text'>

<sup>Originally posted by **amitnil-developer** July  4, 2022</sup>
Greetings,

I have recently come across a situation where I need to migrate my webapp(_angular, nodeJs_)  from FIrebase (cloud functions etc).. to MongoDb and I stumbled upon AceBase which by description looks perfect. Whats the best way to go about this.

Thanks
amit....
</div>

**Comment by appy-one** [comment]
Hi Amit, sorry for replying so late, I've been on holiday! 🌴

Awesome you want to migrate to AceBase! I don't know what your particular usecase is, but much of AceBase's SDK is compatible with Firebase's realtime db Javascript SDK. One of the first steps you'd want to take is exporting your data from Firebase, and importing it into either a local AceBase database, or a remote AceBaseServer instance. Since you mentioned cloud functions, you probably want to run a Node.js app in the cloud or your own server: check out how to [setup an AceBaseServer](https://github.com/appy-one/acebase-server). You can use an [AceBaseClient](https://github.com/appy-one/acebase-client) within your Angular app to connect to your server.

I am closing this issue, I'll copy this reply to your original discussion.
If you have more specific questions, don't hesitate to ask in that discussion. I'm happy to help!

[![Spread the word](https://user-images.githubusercontent.com/26569719/169265089-3d593555-e1ad-4390-986b-877ac2c38a47.svg)](https://twitter.com/intent/tweet?button=&url=https://github.com/appy-one/acebase&text=I'm+using+@AcebaseRealtime+in+my+project+to+make+my+life+easier!&button=)  [![contribute](https://user-images.githubusercontent.com/26569719/169265318-30c4c6a5-7c89-46a0-a7a2-ef433a8192f4.svg)](https://github.com/appy-one/acebase#contributing)  [![Sponsor AceBase](https://user-images.githubusercontent.com/26569719/168233053-8e56b243-4140-40ab-9a30-4cb3cc149bfe.svg)](https://github.com/sponsors/appy-one)
