### ISSUE TITLE
Using filter "in" with another filter on indexed bigInt does not return all values

### ISSUE THREAD

**Issue by Mitsichury** [appy-one/acebase#152]
Hi :)

I have trouble getting all values when using indexed BigInt value and combining query filters.
You can find a test that reproduce ths issue here : https://github.com/appy-one/acebase/pull/151/files
Hope it helps you, thank you for your amazing app :)

Best regards,
Mitsi.

**Comment by appy-one** [comment]
Thanks Mitsi, after some digging, it appears to be a bug in the serialization of BigInts to binary format and/or vice versa. I'll have to fix that algorithm.

**Comment by appy-one** [comment]
Fix has been published in acebase@1.24.2 and acebase-server@1.13.1

Note that you'll have to update the BigInt values in your db because some have been stored incorrectly!

[![Sponsor AceBase](https://user-images.githubusercontent.com/26569719/168233053-8e56b243-4140-40ab-9a30-4cb3cc149bfe.svg)](https://github.com/sponsors/appy-one) [![Spread the word](https://user-images.githubusercontent.com/26569719/169265089-3d593555-e1ad-4390-986b-877ac2c38a47.svg)](https://twitter.com/intent/tweet?button=&url=https://github.com/appy-one/acebase&text=I'm+using+@AcebaseRealtime+in+my+project+to+make+my+life+easier!&button=)  [![contribute](https://user-images.githubusercontent.com/26569719/169265318-30c4c6a5-7c89-46a0-a7a2-ef433a8192f4.svg)](https://github.com/appy-one/acebase#contributing)

**Comment by Mitsichury** [comment]
Hi :) 
Sorry for the late answer, I've updated to the last version 1.24.4, my tests still don't work if I create indexes on Bigint and I apply filters on it. But it works really great without indexes. I don't know why for now because your unit tests are green, I'll try to reproduce the issue.
Thank you for your amazing work :) !

**Comment by Mitsichury** [comment]
I've found how to reproduce it ! 
I've modified a test to make it close to my usage : https://github.com/appy-one/acebase/pull/159/files 

- Empty db
- Creating indexes
- Adding some data by unit call instead of set collection (like if I did it with http requests)
- Requesting data 

I don't know if it's a bug or a misusage from me.

Thank you,
Mitsi.

**Comment by appy-one** [comment]
Thanks for your PR, I'm on it!

**Comment by appy-one** [comment]
Hi Mitsi, I've fixed the issue and released new version v1.24.5
Note that the code in the PR does contain an async issue with `forEach`, see my comments there.
Let me know if it all works!

**Comment by Mitsichury** [comment]
Hi @appy-one thank you for your review and your fix, it's working really good :D 
Best regards,
Mitsi.
