### ISSUE TITLE
Can't import { AceBase } with moduleResolution="nodenext" in tsconfig.json

### ISSUE THREAD

**Issue by Septh** [appy-one/acebase#219]
This is a follow-up to #203 which was closed as stale.

As noted there, the error is `error TS2305: Module '"acebase"' has no exported member 'AceBase'`. There is no error when `moduleResolution` is set to `"node"`.

AceBase `v1.28.2`, tested with both TypeScript `4.9.5` and `5.0.4`.

**Comment by appy-one** [comment]
This has been fixed in v1.28.3

[![Sponsor AceBase](https://user-images.githubusercontent.com/26569719/168233053-8e56b243-4140-40ab-9a30-4cb3cc149bfe.svg)](https://github.com/sponsors/appy-one) [![Spread the word](https://user-images.githubusercontent.com/26569719/169265089-3d593555-e1ad-4390-986b-877ac2c38a47.svg)](https://twitter.com/intent/tweet?button=&url=https://github.com/appy-one/acebase&text=I'm+using+@AcebaseRealtime+in+my+project+to+make+my+life+easier!&button=)  [![contribute](https://user-images.githubusercontent.com/26569719/169265318-30c4c6a5-7c89-46a0-a7a2-ef433a8192f4.svg)](https://github.com/appy-one/acebase#contributing)
